services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - ${SERVER_PORT}:3000
    depends_on:
      - db
    volumes:
      - ./src:/app/src
  
  db:
    image: mysql
    restart: always
    ports: 
      - ${DB_PORT}:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}

volumes:
  db-data:
  


